### ISSUE TITLE
Incorrect conversion from Inches to centimeters

### ISSUE THREAD

**Issue by tomdstone** [StevenLShafer/stanpumpR#122]
Hello, it looks like the wrong unit conversion between inches and cm, shouldn't it be 2.54, not 2.56?
https://github.com/StevenLShafer/stanpumpR/blob/ffc01a9e90e5fa3ade305758c64803320dfbb60f/R/globalVariables.R#L12-L13

**Comment by StevenLShafer** [comment]
Dear Tom:

Yes indeed!

I’ll go ahead and fix this.

Thanks,

Steve

From: tomdstone ***@***.***>
Sent: Saturday, February 18, 2023 5:24 AM
To: StevenLShafer/stanpumpR ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [StevenLShafer/stanpumpR] Incorrect conversion from Inches to centimeters (Issue #122)


Hello, it looks like the wrong unit conversion between inches and cm, shouldn't it be 2.54, not 2.56?
https://github.com/StevenLShafer/stanpumpR/blob/ffc01a9e90e5fa3ade305758c64803320dfbb60f/R/globalVariables.R#L13
